<?php $this->headTitle($title = 'Password retrieval') ?>
<div class="page-header">
    <h3><?php echo $this->escapeHtml($title)?></h3>
</div>
<div class="row">
    <div class="col-sm-6 col-md-6">
        <p>Please enter the login or email that you used to log on to the site.</p>
        <?php $form = $form->setAttribute('class', 'form')->prepare() ?>
        <?php echo $this->form()->openTag($form) ?>
        <div class="form-group<?php if(count($form->get('email')->getMessages())):?> has-error<?php endif?>">
            <label class="control-label" for="email">Email</label>
            <div class="controls">
                <?php echo $this->formElement($form->get('email')->setAttribute('class', 'form-control'))?>
                <?php echo $this->formElementErrors($form->get('email'), array('class' => 'help-block'));?>
            </div>
        </div>
        <div class="form-group">
            <div class="controls">
                <button class="btn btn-lg btn-primary">Next</button>
            </div>
        </div>
        <?php echo $this->form()->closeTag()?>
    </div>
</div>