<?php echo $this->doctype(); ?>
<?php $themeName = $this->themeName('backend');?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Admin control panel'))->setSeparator(' - ')->setAutoEscape(false)."\n" ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')."\n" ?>
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('/favicon.ico')))
            ->setSeparator("\n\t")
            ->prependStylesheet($this->basePath('/themes/'.$themeName.'/backend/css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('/themes/'.$themeName.'/backend/css/style.css'))."\n"?>
        <?php echo $this->headScript()->setSeparator("\n\t")
            ->prependFile($this->basePath('/themes/'.$themeName.'/backend/js/common.js'))
            ->prependFile($this->basePath('/themes/'.$themeName.'/backend/js/bootstrap.min.js'))
            ->prependFile($this->basePath('/themes/'.$themeName.'/backend/js/jquery.min.js'))."\n" ?>
        <base href="<?php echo $this->basePath?>"/>
    </head>
    <body>
        <div class="wrapper">
            <header class="navbar navbar-static-top navbar-default" id="top" role="banner">
                <div class="container">
                    <div class="navbar-header">
                        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a href="/" class="navbar-brand">BerryShop</a>
                    </div>
                    <nav class="collapse navbar-collapse" role="navigation">
                        <?php echo $this->navigation('navigation/admin')->menu()->setUlClass('nav navbar-nav'); ?>
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="/">Index page</a></li>
                            <li><a href="/auth/logout">Logout</a></li>
                        </ul>
                    </nav>
                </div>
            </header>
            <div class="navbar-push"></div>
            <div class="container">
                <?php echo $this->flashMessage()->setUIClass('alert')?>
                <?php echo $this->content; ?>
            </div>
            <div class="push"></div>
        </div>
        <footer>
            <div class="container">
                <p>Designed and built with all the love in the world by <a href="https://github.com/andresayak">andresayak</a></p>
                <p>Maintained by the core team with the help of our contributors</p>
                <p>Code licensed under MIT</p>
            </div>
        </footer>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
