<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Shopberry'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>
    <script>
        $(document).ready(function() {
            $('.navbar .nav ul').addClass('dropdown-menu'); 
            $.each($('.navbar .nav ul'), function(){
                var element = $(this).parent().children('a');
                if(!$(element).hasClass('level-0')){
                    var label = $(element).html()+' <span class="icon-chevron-right"></span>'
                    $(element).html(label);
                }
            });
            $('.navbar .nav li').hover(function(){
                var ul = $(this).find('> ul');
                if($(this).parent().css('position')=='absolute'){
                    $(ul).show().css({left:($(this).parent().width()-15)+'px', top:'-4px'});
                }else{
                    $(ul).show().css({left:'0px',top:'35px'});
                }	
            }, function(){
                $(this).find('> ul').hide();
            });
        });
    </script>
    </head>
    <body>
        <div class="wrapper">
            <header class="navbar navbar-static-top bs-docs-nav" id="top" role="banner">
                <div class="container">
                    <div class="navbar-header">
                        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a href="../" class="navbar-brand">Bootstrap</a>
                    </div>
                    <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
                        <ul class="nav navbar-nav">
                            <li>
                                <a href="../getting-started">Getting started</a>
                            </li>
                            <li class="active">
                                <a href="../css">CSS</a>
                            </li>
                            <li>
                                <a href="../components">Components</a>
                            </li>
                            <li>
                                <a href="../javascript">JavaScript</a>
                            </li>
                            <li>
                                <a href="../customize">Customize</a>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="http://expo.getbootstrap.com" onclick="ga('send', 'event', 'Navbar', 'Community links', 'Expo');">Expo</a></li>
                            <li><a href="http://blog.getbootstrap.com" onclick="ga('send', 'event', 'Navbar', 'Community links', 'Blog');">Blog</a></li>
                        </ul>
                    </nav>
                </div>
            </header>
            <div class="navbar-push"></div>
            <div class="container">
                <?php echo $this->flashMessage()->setUIClass('alert')?>
                <?php echo $this->content; ?>
            </div>
            <div class="push"></div>
        </div>
        <footer>
            <div class="container">
                <hr>
                <p>&copy; <?php echo $year_from = 2013?><?php echo ($year_to = date('Y') and $year_to > $year_from)?' - '.$year_to:''?> by Andrey Sayak. <?php echo $this->translate('All rights reserved.') ?></p>
            </div>
        </footer>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
