<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Shopberry'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>
    <script>
        $(document).ready(function() {
            $('.navbar .nav ul').addClass('dropdown-menu'); 
            $.each($('.navbar .nav ul'), function(){
                var element = $(this).parent().children('a');
                if(!$(element).hasClass('level-0')){
                    var label = $(element).html()+' <span class="icon-chevron-right"></span>'
                    $(element).html(label);
                }
            });
            $('.navbar .nav li').hover(function(){
                var ul = $(this).find('> ul');
                if($(this).parent().css('position')=='absolute'){
                    $(ul).show().css({left:($(this).parent().width()-15)+'px', top:'-4px'});
                }else{
                    $(ul).show().css({left:'0px',top:'35px'});
                }	
            }, function(){
                $(this).find('> ul').hide();
            });
        });
    </script>
    </head>
    <body>
        <div class="wrapper">
            <div class="navbar navbar-inverse navbar-fixed-top">
                <div class="navbar-inner">
                    <div class="container">
                        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </a>
                        <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Shopberry') ?></a>
                        <div class="nav-collapse collapse">
                            <?php echo $this->navigation('navigation/admin')->menu()->setUlClass('nav')->setMinDepth(1)?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="navbar-push"></div>
            <div class="container">
                <?php echo $this->flashMessage()->setUIClass('alert')?>
                <?php echo $this->content; ?>
            </div>
            <div class="push"></div>
        </div>
        <footer>
            <div class="container">
                <hr>
                <p>&copy; <?php echo $year_from = 2013?><?php echo ($year_to = date('Y') and $year_to > $year_from)?' - '.$year_to:''?> by Andrey Sayak. <?php echo $this->translate('All rights reserved.') ?></p>
            </div>
        </footer>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
