<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('BerryShop'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
            ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
            ->prependStylesheet($this->basePath() . '/css/style.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>
        <?php
        echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/common.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js') ?>
    </head>
    <body>
        <div class="wrapper">
            <header class="navbar navbar-static-top bs-docs-nav" id="top" role="banner">
                <div class="container">
                    <div class="navbar-header">
                        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a href="../" class="navbar-brand">BerryShop</a>
                    </div>
                    <nav class="collapse navbar-collapse" role="navigation">
                        <ul class="nav navbar-nav">
                            <li class="active">
                                <a href="../css">News</a>
                            </li>
                            <li>
                                <a href="../components">Brands</a>
                            </li>
                            <li>
                                <a href="../javascript">About</a>
                            </li>
                            <li>
                                <a href="../customize">Feedback</a>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="/auth/login">Login</a></li>
                            <li><a href="/auth/signup">Sign up</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Shopping cart (<b>1 items</b>)</a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="#">Sony t100</a></li>
                                </ul>
                            </li>
                        </ul>
                    </nav>
                    <div class="navbar-category row">
                        <div class="col-sm-8 col-md-10">
                            <?php echo $this->navigation('navigation/category')->menu()->setUlClass('nav navbar-nav'); ?>
                        </div>
                        <div class="col-sm-4 col-md-2 search-block">
                            <form>
                                <div class="form-group has-feedback">
                                    <input placeholder="Search..." type="text" class="form-control" id="inputSeacrh">
                                    <span class="glyphicon glyphicon-search form-control-feedback"></span>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </header>
            <div class="container">
                <?php echo $this->flashMessage()->setUIClass('alert')?>
                <?php echo $this->content; ?>
            </div>
            <div class="push"></div>
        </div>
        <footer>
            <div class="container">
                <p>Designed and built with all the love in the world by <a href="https://github.com/andresayak">andresayak</a></p>
                <p>Maintained by the core team with the help of our contributors</p>
                <p>Code licensed under MIT</p>
                <hr>
                <?php echo $this->navigation('navigation/footer')->menu()->setUlClass('footer-links')?>
            </div>
        </footer>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
